[package]
name = "soos-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "soos-cli \"20 inches in cm\" -- CLI for the soos calculator engine"

[[bin]]
name = "soos-cli"
path = "src/main.rs"

[dependencies]
soos-core = { path = "../soos-core" }
serde_json = "1"
